### ISSUE TITLE
Dialog does not launch on Monterey due to DND privacy change

### ISSUE THREAD

**Issue by bradtchapman** [dnikles/JMDG#1]
https://github.com/dnikles/JMDG/blob/959ab51af8d46a139620a84133985ace403c970b/jmdg.sh#L5

This is noted in @bartreardon's repo for swiftDialog: on MacOS Monterey, swiftDialog will not launch because it thinks the computer is in DND mode all the time.  The truth is that it cannot read the DND state anymore because of a security change by Apple.  

Bart has not requested the PPPC entitlement to read focus states and instead recommends admins put the `-d` flag in the arguments list for `dialog`.  

My proposed fix:

`/usr/local/bin/dialog -d`

**Comment by dnikles** [comment]
I haven't run into this on Monterey, but it doesn't look like it will hurt anything, so I threw -d on all calls of dialog
https://github.com/dnikles/JMDG/commit/4385d6f6436cb7574b4c8eeddf453038b6be17fb

**Comment by bradtchapman** [comment]
Probably because you haven't signed into iCloud on a test system.  Once you do, DND behavior changes.  @bartreardon ran into this due to Apple's changes to Focus modes.
