### ISSUE TITLE
Window should be moveable.

### ISSUE THREAD

**Issue by bradtchapman** [dnikles/JMDG#2]
Please add the `--moveable` flag to your invocation of `dialog`.  By default, the window launches in the center of the screen and cannot be moved.  Please consider changing this.

**Comment by dnikles** [comment]
All calls to dialog are now moveable 
https://github.com/dnikles/JMDG/commit/efb5bb5b8dbf0ac755618e94cae81a102a652208

**Comment by bradtchapman** [comment]
Thank you!
